name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'main'

permissions:
  packages: write

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Boost
        uses: actions/checkout@v3
        with:
          path: 'ext-boost'

      - name: Checkout ext-builder
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/ext-builder
          path: 'ext-builder'

      - name: Build Boost
        run: ./ext-builder/build.py ./ext-boost --image ghcr.io/tst-race/ext-builder:initial-setup --target linux-x86_64
