name: Build Boost
on: [push]
jobs:
  build-linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v3
        with:
          path: '${{ runner.workspace }}/boost_*.tar.gz'
          key: 'boost-1.73.0'

      - uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - uses: egor-tensin/build-boost@v1
        with:
          version: 1.73.0
          libraries: headers random system thread filesystem chrono atomic date_time regex
          toolset: clang
          platform: x64
          configuration: Release
