name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'main'

permissions:
  packages: write

jobs:
  build-boost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Boost
        uses: actions/checkout@v3

      - name: Build Linux x86_64
        uses: ${{ github.repository_owner }}/build-ext-action@v1
        with:
          target: linux-x86_64
